In [1]:
import pandas as pd
import numpy as np

In [2]:
#Generate marks for 50 students.

np.random.randint(1,100,51)

array([31, 62, 81, 44, 28, 23, 40, 37, 66, 33, 99, 58, 90, 90, 56, 93, 13,
       95, 26, 29,  3, 79, 92, 44, 32, 62, 17, 54, 52, 21, 95, 66, 79,  7,
       62, 66, 36, 89, 81, 78, 44, 87, 85, 47, 94, 89, 44, 74, 31, 50, 65],
      dtype=int32)

In [ ]:
#Calculate total, average, highest, lowest.

marks = np.random.randint(0, 101, 50)

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

In [3]:
#Count above 75, below 35, between 35-75.

marks = np.random.randint(0,101,50)

print("Above 75:", np.sum(marks > 75))
print("Below 35:", np.sum(marks < 35))
print("35 to 75:", np.sum((marks >= 35) & (marks <= 75)))

Above 75: 10
Below 35: 16
35 to 75: 24


In [5]:
#Assign grades.

marks = np.array([95,82,75,68,55,30])
grade = []

for i in marks:
    if i>=90:
        grade.append("A")
    elif i>=75:
        grade.append("B")
    elif i>=60:
        grade.append("C")
    elif i>=35:
        grade.append("D")
    else:
        grade.append("Fail")
print(marks)
print(grade)

[95 82 75 68 55 30]
['A', 'B', 'B', 'C', 'D', 'Fail']


In [6]:
#Display top 5 marks.

marks = np.random.randint(0, 101, 50)
marks.sort()
print("Top 5 Marks:")
print(marks[-5:])

[87 88 89 98 99]


In [7]:
#Display bottom 5 marks.

marks = np.random.randint(0, 101, 50)
marks.sort()
print("Bottom 5 Marks:")
print(marks[:5])

Bottom 5 Marks:
[3 3 4 5 6]


In [8]:
#Find median and standard deviation

marks = np.random.randint(0, 101, 50)

print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))

Median: 51.0
Standard Deviation: 28.47247091490305


In [10]:
#Create a 5-subject marks matrix and calculate totals

marks = np.random.randint(35, 101, (5,5))

print("Marks Matrix:")
print(marks)
total = np.sum(marks, axis=1)
print("Total Marks:",total)

Marks Matrix:
[[52 98 66 76 47]
 [94 89 58 80 96]
 [86 59 68 49 99]
 [59 99 77 60 47]
 [88 46 82 50 60]]
Total Marks: [339 417 361 342 326]


In [11]:
#Find topper in each subject

marks = np.random.randint(35, 101, (5,5))

print("Marks Matrix:")
print(marks)
print("Highest marks in each subject:",np.max(marks, axis=0))

Marks Matrix:
[[80 54 56 96 93]
 [98 47 72 99 80]
 [51 73 59 45 61]
 [66 54 85 99 36]
 [79 69 37 59 83]]
Highest marks in each subject: [98 73 85 99 93]


In [12]:
#Generate report card with Total, Average, Percentage and Grade

marks = np.random.randint(35, 101, (5,5))

print("Marks:")
print(marks)

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
percentage = total / 500 * 100

print("\nReport Card")

for i in range(5):
    if percentage[i] >= 80:
        grade = "A"
    elif percentage[i] >= 60:
        grade = "B"
    elif percentage[i] >= 40:
        grade = "C"
    else:
        grade = "Fail"

    print("Student", i + 1)
    print("Total:", total[i])
    print("Average:", average[i])
    print("Percentage:", percentage[i])
    print("Grade:", grade)
    print()

Marks:
[[59 94 36 90 67]
 [66 40 61 78 77]
 [43 97 97 98 49]
 [60 91 61 42 50]
 [81 41 70 67 66]]

Report Card
Student 1
Total: 346
Average: 69.2
Percentage: 69.19999999999999
Grade: B

Student 2
Total: 322
Average: 64.4
Percentage: 64.4
Grade: B

Student 3
Total: 384
Average: 76.8
Percentage: 76.8
Grade: B

Student 4
Total: 304
Average: 60.8
Percentage: 60.8
Grade: B

Student 5
Total: 325
Average: 65.0
Percentage: 65.0
Grade: B

